apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  # type: LoadBalancer # set the type of Service
  selector:
    matchLabels:
      app: frontend # referencing the Pod's label
  strategy:
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: reeceqa/python-frontend
        ports:
          - name: http
            containerPort: 5000
            protocol: TCP
---
# Pod config below
# apiVersion: v1
# kind: Pod
# metadata:
#   name: frontend
#   labels:
#     app: frontend
# spec:
#   containers:
#     - name: frontend
#       image: reeceqa/python-frontend
#       ports:
#         - containerPort: 5000
          
