apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:latest
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: mysql-password
      - name: MYSQL_DATABASE
        value: mydatabase
    ports: 
    - containerPort: 3306